"""Add profile fields and professional status

Revision ID: 30e45d8cfaf8
Revises: 6959187dee6b
Create Date: 2024-08-03 02:38:36.349764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e45d8cfaf8'
down_revision: Union[str, None] = '6959187dee6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
